before_script:
  - test -d node_modules || ln -s ~/node_modules node_modules
  - yarn

build_test_package:
  script:
  - npm run build-test
  - tar czvf top.saas.agent.vue.tar.gz -C dist/ .
  - uploadPackage.py -p top.saas.agent-vue2 -n test -v "$CI_BUILD_ID" -g 'top.saas.agent.vue.tar.gz' --publish True
  tags:
  - frontend
  only:
    - develop

build_demo_package:
  script:
  - npm run build-demo
  - tar czvf top.saas.agent.vue.tar.gz -C dist/ .
  - uploadPackage.py -p top.saas.agent-vue2 -n demo -v "$CI_BUILD_ID" -g 'top.saas.agent.vue.tar.gz' --publish True
  tags:
  - frontend
  only:
    - develop

build_dev_package:
  script:
  - npm run build-dev
  - tar czvf top.saas.agent.vue.tar.gz -C dist/ .
  - uploadPackage.py -p top.saas.agent-vue2 -n dev -v "$CI_BUILD_ID" -g 'top.saas.agent.vue.tar.gz' --publish True
  tags:
  - frontend
  only:
    - develop

build_beta_package:
  script:
  - npm run build-beta
  - tar czvf top.saas.agent.vue.tar.gz -C dist/ .
  - uploadPackage.py -p top.saas.agent-vue2 -n beta -v "$CI_BUILD_ID" -g 'top.saas.agent.vue.tar.gz'
  only:
    - /^release.*$/
  tags:
  - frontend

build_ga_package:
  script:
  - npm run build-release
  - tar czvf top.saas.agent.vue.tar.gz -C dist/ .
  - uploadPackage.py -p top.saas.agent-vue2 -n ga -v "$CI_BUILD_ID" -g 'top.saas.agent.vue.tar.gz'
  only:
    - /^release.*$/
  tags:
  - frontend
