before_script:
  - test -d node_modules || ln -s ~/node_modules node_modules
  
build_test_package:
  script:
  - gulp publish --test
  - tar czvf tops.sass.oa.tar.gz -C dist/ .
  - uploadPackage.py -p tops.sass.oa -n test -v "$CI_BUILD_ID" -g 'tops.sass.oa.tar.gz' --publish True
  tags:
  - frontend
  only:
    - develop

build_demo_package:
  script:
  - gulp publish --demo
  - tar czvf tops.sass.oa.tar.gz -C dist/ .
  - uploadPackage.py -p tops.sass.oa -n demo -v "$CI_BUILD_ID" -g 'tops.sass.oa.tar.gz' --publish True
  tags:
  - frontend
  only:
    - develop

build_dev_package:
  script:
  - gulp publish --dev
  - tar czvf tops.sass.oa.tar.gz -C dist/ .
  - uploadPackage.py -p tops.sass.oa -n dev -v "$CI_BUILD_ID" -g 'tops.sass.oa.tar.gz' --publish True
  tags:
  - frontend
  only:
    - develop

build_beta_package:
  script:
  - gulp publish --beta
  - tar czvf tops.sass.oa.tar.gz -C dist/ .
  - uploadPackage.py -p tops.sass.oa -n beta -v "$CI_BUILD_ID" -g 'tops.sass.oa.tar.gz'
  only:
    - /^release.*$/
  tags:
  - frontend
  
build_ga_package:
  script:
  - gulp publish --release
  - tar czvf tops.sass.oa.tar.gz -C dist/ .
  - uploadPackage.py -p tops.sass.oa -n ga -v "$CI_BUILD_ID" -g 'tops.sass.oa.tar.gz'
  only:
    - /^release.*$/
  tags:
  - frontend